// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvtY6lzdQjG_2D9MZEqlw_n7393MkPrHU',
    appId: '1:477470132170:web:3933b1b2189a052d20f133',
    messagingSenderId: '477470132170',
    projectId: 'docsearchweb-780db',
    authDomain: 'docsearchweb-780db.firebaseapp.com',
    databaseURL: 'https://docsearchweb-780db-default-rtdb.firebaseio.com',
    storageBucket: 'docsearchweb-780db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvtNQiY2KQBVhNjkaXlQgueoXAKTNEfKY',
    appId: '1:477470132170:android:04e830130f151f2320f133',
    messagingSenderId: '477470132170',
    projectId: 'docsearchweb-780db',
    databaseURL: 'https://docsearchweb-780db-default-rtdb.firebaseio.com',
    storageBucket: 'docsearchweb-780db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkIvDwPDtctVTVmX35tWdPo9poLbY0wNk',
    appId: '1:477470132170:ios:ecb2188811f82b1520f133',
    messagingSenderId: '477470132170',
    projectId: 'docsearchweb-780db',
    databaseURL: 'https://docsearchweb-780db-default-rtdb.firebaseio.com',
    storageBucket: 'docsearchweb-780db.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkIvDwPDtctVTVmX35tWdPo9poLbY0wNk',
    appId: '1:477470132170:ios:ecb2188811f82b1520f133',
    messagingSenderId: '477470132170',
    projectId: 'docsearchweb-780db',
    databaseURL: 'https://docsearchweb-780db-default-rtdb.firebaseio.com',
    storageBucket: 'docsearchweb-780db.appspot.com',
    iosBundleId: 'com.example.test',
  );
}
